NativeToMe-master/NativeToMe/urls.py
from django.contrib import admin
from django.urls import path, include
####
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')), #functioning as home
    path('accounts/', include('accounts.urls'), name = 'accounts'),
    path('tribes/', include('tribes.urls'), name='tribes'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NativeToMe-master/accounts/urls.py
from django.urls import path

app_name = 'accounts'

from . import views
urlpatterns = [
    path('login.html/', views.loginView, name='loginView'),
    path('logout.html/', views.logoutView, name='logoutView'),
    path('register.html/', views.registerView, name='registerView'),
    path('userprofile/userprofile.html/', views.profileView, name='profileView'),
]

NativeToMe-master/home/urls.py
from django.urls import path

app_name = 'home'

from . import views
urlpatterns = [
    path('', views.homeView),
]

NativeToMe-master/tribes/urls.py
from django.urls import path

app_name = 'tribes'

from . import views
urlpatterns = [
    path('tribeHomePage.html/<tribeID>/', views.tribeHomePage, name='tribeHomePage'),
    path('tribeCreatePage.html/', views.tribeCreate, name='tribeCreate'),
    path('tribeSearchPage.html/', views.tribeSearchPage, name='tribeSearchPage'),
    path('tribeManagePage.html/<tribeID>/', views.tribeManagePage, name='tribeManagePage'),
    path('tribeHousePage.html/<tribeID>/', views.tribeHousePage, name='tribeHousePage')
]

NativeToMe-master/tribes/models.py
from random import randint
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User


"""This is the blueprint for a tribe table in the database"""




class Tribe(models.Model):
    objects = models.Manager()
    tribeID = models.IntegerField(primary_key=True)
    tribeName = models.CharField(max_length=50)
    # How long its been a tribe
    dateOfCreation = models.DateField(default=timezone.now)
    # Location
    location = models.CharField(max_length=30)
    # Privacy
    choices = [('Public', 'Private'), ('Private', 'Public')]
    privacyMode = models.CharField(max_length=7, choices=choices, default='Private')
    # Number of members
    numOfMembers = models.IntegerField(default=1)
    # Description
    description = models.TextField(blank=True)
    # owner, tribe founder(s)
    tribeOwner = models.CharField(max_length=50)
    # list of tribe members
    tribeMembers = models.ManyToManyField(User, related_name="tribeMembers")

    def tribe_present(tribeName):
        if Tribe.objects.filter(tribeName=tribeName).exists():
            return True
        else:
            return False

    def tribe_search(tribeName):
        q = Q()
        for t in Tribe:
            q |= Q(name_icontains=t)
            return Tribe.objects.filter(q)

    def __str__(self):
        """String for representing the Model object 'tribeName'."""
        return self.tribeName



class House(models.Model):
    objects = models.Manager()
    houseName = models.CharField(default='', max_length=200)
    houseID = models.IntegerField(primary_key=True, default=randint(0,1000))
    houseInTribe = models.ManyToManyField(Tribe)
    # How long its been a tribe
    dateOfCreation = models.DateField(default=timezone.now)
    # Description
    description = models.TextField(blank=True)
    # owner, tribe founder(s)
    houseCreator = models.OneToOneField(User, on_delete=models.CASCADE, default=User.is_active)

    def __str__(self):
        """String for representing the Model object 'houseName'."""
        return self.houseName


class Posts(models.Model):
    """NEEDS IMPROVEMENT"""
    objects = models.Manager()
    title = models.CharField(default='', max_length=200)
    postID = models.IntegerField(primary_key=True, default=randint(0,1000))
    #User who posted
    tribePosterID = models.ManyToManyField(User, related_name="tribePosterID")
    #What tribe does this post belong to
    postTribeID = models.ManyToManyField(Tribe, related_name="postTribeID")
    image = models.ImageField(default='blankProfile.jpg', upload_to='profile_pics')
    description = models.TextField(blank=True)
    dateOfCreation = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title

class JoinRequest(models.Model):
    objects = models.Manager()
    requestingUser = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    tribeIDToJoin = models.ManyToManyField(Tribe, related_name="tribeIDToJoin")
    requestMessage = models.TextField(max_length=300, default='')

    def __str__(self):
        return self.requestingUser.username

class Events(models.Model):
    objects = models.Manager()
    postingUser = models.ForeignKey(User, on_delete=models.CASCADE)
    tribeEvent = models.OneToOneField(Tribe, primary_key=True,on_delete=models.CASCADE, default=None)
    requestMessage = models.TextField(max_length=300, default='')
    image = models.ImageField(default='blankProfile.jpg', upload_to='profile_pics')
    description = models.TextField(blank=True)
    dateOfCreation = models.DateField(default=timezone.now)

NativeToMe-master/tribes/forms.py
from django import forms
from .models import Tribe

"""Create tribe Form"""
class createTribeForm(forms.Form):
    fields = ['tribeName', 'location', 'privacyMode', 'description']
    tribeName = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), max_length=100)
    location = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), max_length=50)
    choices = [('Public', 'Public'), ('Private', 'Private')]
    privacyMode = forms.ChoiceField(choices=choices)
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))

    """Search for a tribe"""
class searchTribeForm(forms.Form):
    searchField = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=100)


class editTribeForm(forms.Form):
    fields = ['tribeName','description']
    tribeName = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}), max_length=100 )
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))

class createTribePostForm(forms.Form):
    fields = ['title', 'description']
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=100)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    #image = forms.ImageField(widget=forms.ImageField)

class requestToJoin(forms.Form):
    fields = ['message']
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

NativeToMe-master/tribes/views.py
from datetime import datetime
from random import randint
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import *
from django.db.models import Q
from .models import Tribe, Posts, JoinRequest, House

#Global list of requests for tribe owner

# Create your views here.
"""Python functions that take a request and render a web page"""
@login_required
def tribeHomePage(request, tribeID):
    """Grab Data"""
    current_user = User.objects.get(username=request.user)
    #Tribe object
    tribe = Tribe.objects.get(pk=tribeID)
    #Posts object
    posts = Posts.objects.filter(postTribeID=tribeID)
    createPostForm = createTribePostForm(request.POST)
    joinForm = requestToJoin(request.POST)
    #Collection of all tribeMembers
    members = tribe.tribeMembers.all()
    print(members)
    print(posts)
    #check if current_user in the given tribe's list of members
    if current_user in members:
        inTribe = True
    else:
        inTribe = False
    context = {'tribe': tribe,
               'createPostForm': createPostForm,
               'joinForm': joinForm,
               'members': members,
               'inTribe': inTribe,
               'post': posts, }

    if request.method == "GET":
        print("tribeHomePage GET")
        joinForm = requestToJoin(request.POST)
        context = {'tribe' : tribe,
                   'createPostForm' : createPostForm,
                   'joinForm' : joinForm,
                   'members':members,
                   'inTribe':inTribe,
                   'posts':posts,}
        return render(request, 'tribes/tribeHomePage.html/', context)
    elif request.method == "POST" and inTribe == True:
        """Create Post"""
        print("tribeHomePage POST")
        if createPostForm.is_valid():
            print("New post")
            post = Posts()
            post.title = createPostForm.cleaned_data.get("title")
            post.description = createPostForm.cleaned_data.get("description")
            post.dateOfCreation = datetime.now()
            print(tribe)
            print(current_user)
            print(post.title)
            post.save()
            post.postTribeID.add(tribe)
            post.tribePosterID.add(current_user)

            """Update context"""
            posts = Posts.objects.filter(postTribeID=tribeID)
            tribe = Tribe.objects.get(pk=tribeID)

            context = {'tribe': tribe,
                       'createPostForm': createPostForm,
                       'members': members,
                       'inTribe': inTribe,
                       'posts': posts, }
            print(posts)
            return render(request, 'tribes/tribeHomePage.html/', context)
        else:
            print("Invalid form!")
            return render(request, 'tribes/tribeHomePage.html/', context)
    if request.method == "POST" and inTribe == False:
        print("Request to join!")
        if joinForm.is_valid():
            join = JoinRequest()
            join.requestingUser = current_user
            join.requestMessage = joinForm.cleaned_data.get("message")
            join.save()
            join.tribeIDToJoin.add(tribe)

            """Update context"""
            posts = Posts.objects.filter(postTribeID=tribeID)
            tribe = Tribe.objects.get(pk=tribeID)

            requests = JoinRequest.objects.filter(tribeIDToJoin = tribe)
            print(requests)
            context = {'tribe': tribe,
                       'createPostForm': createPostForm,
                       'members': members,
                       'inTribe': inTribe,
                       'requests':requests,
                       'posts': posts, }
            return render(request, 'tribes/tribeHomePage.html/', context)
        else:
            print("User is not part of the tribe. Cannot post")
            return render(request, 'tribes/tribeHomePage.html/', context)
    else:
        return render(request, 'tribes/tribeHomePage.html/', context)


def tribeSearchPage(request):
    if request.method == "GET":
        queryset_list = Tribe.objects.all()
        query = request.GET.get("searchField")
        if query:
            match = queryset_list.filter(Q(tribeName__icontains=query))
            context = { "object_list":match}
            if match:
                return render(request, 'tribes/tribeSearchPage.html/', context)
            else:
                return render(request, 'tribes/tribeSearchPage.html/', {})
        return render(request, 'tribes/tribeSearchPage.html/', {})


def tribeCreate(request):
    current_user = User.objects.get(username=request.user.username)
    print(current_user)
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = createTribeForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            tribe = Tribe()
            # process the data in form.cleaned_data as required
            tribe.tribeID = randint(0,1000)
            tribe.tribeName = form.cleaned_data.get("tribeName")
            tribe.location = form.cleaned_data.get("location")
            tribe.description = form.cleaned_data.get("description")
            tribe.choices = form.cleaned_data.get("choices")
            tribe.privacyMode = form.cleaned_data.get("privacyMode")
            """tribe.tribeOwner = request.user does not work because of incompatible types"""
            """tribe.tribeOwner = UserProfile.user"""
            tribe.tribeOwner = current_user.username
            tribe.save()
            #When a tribe is created. The person who creates it is in the tribe. Add member.
            tribe.tribeMembers.add(current_user)

            if Tribe.tribe_present(tribe.tribeName) == True:
                print("Successfully created " + tribe.tribeName + "!")
                print(tribe.tribeID)
                print(tribe.tribeOwner)
            # redirect to a new URL:
            return HttpResponseRedirect('/', {'tribe' : tribe })
    else:
        print("Failed to create tribe")
        form = createTribeForm()
    return render(request, 'tribes/tribeCreatePage.html/', {'form':form})


def tribeHousePage(request, tribeID):
    print("Tribe House Page")
    tribe = Tribe.objects.get(pk=tribeID)
    houses = House.objects.all()
    testHouse = House.objects.get(houseID = 1)
    print(testHouse.houseInTribe)
    print(testHouse.dateOfCreation)
    house = House.objects.filter(houseInTribe = tribeID)

    print(house)
    context = {'tribe': tribe,
               'houses': houses,
               }

    return render(request, 'tribes/tribeHousePage.html/', context)

def tribeManagePage(request, tribeID):
    print("Tribe Manage Page")
    tribe = Tribe.objects.get(pk=tribeID)
    form = editTribeForm(request.POST)

    requests = JoinRequest.objects.filter(tribeIDToJoin=tribe)
    print(requests)

    current_user = User.objects.filter(username=request.user.username)
    #collection of tribe members
    members = tribe.tribeMembers.all()
    # check if current_user in the given tribe's list of members
    for current_user in members:
        # set bool variable to use in html render
        if current_user == members:
            inTribe = True
        else:
            inTribe = False

    context = {'tribe': tribe,
               'form': form,
               'members': members,
               'inTribe': inTribe,
               'requests': requests}

    if request.method == "GET":
        """If the user is tribe owner"""
        return render(request, 'tribes/tribeManagePage.html/', context)
    # if this is a POST request we need to process the form data
    elif request.method == "POST" and current_user == tribe.tribeOwner:
        """Update the tribes information"""
        if form.is_valid():
            tribe.tribeName = form.cleaned_data.get("tribeName")
            tribe.description = form.cleaned_data.get("description")
            tribe.save()
            print("Successfully managed tribe")
            return render(request, 'tribes/tribeHomePage.html/', context)
        else:
            print("Manage tribe failed")
            return render(request, 'tribes/tribeManagePage.html/', {'form':form})

NativeToMe-master/templates/tribes/tribeHomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
	<!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="collapse navbar-collapse" style="justify-content-between;" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLeft" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		         Tribes
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdownLeft">
					{% if user.is_authenticated %}
						<a class="dropdown-item" href="/tribes/tribeSearchPage.html">Search Tribes</a>
						{% if user.username == tribe.tribeOwner %}
						<a class="dropdown-item"href="{% url 'tribes:tribeManagePage' tribe.tribeID %}" id="manageTribe">Manage Tribe</a>
						{% endif %}

							{% if inTribe == False %}
							<a class="dropdown-item" data-toggle="modal" href="#exampleModal" id="requestToJoin">Request To Join Tribe</a>
							{% endif %}

						<a class="dropdown-item" href="/tribes/tribeCreatePage.html">Create Tribe</a>
						{% else %}
						<a class="dropdown-item" href="/accounts/login.html">Search Tribes</a>
						<a class="dropdown-item" href="/accounts/login.html">Create Tribe</a>
					{% endif %}
		        </div>
		      </li>
			</ul>
			<ul class="navbar-nav ml-auto">
		      <li class="nav-item dropdown">
		        {% if user.is_authenticated %}
				  <div class="dropdown dropleft" style="margin-right:75px">
  					<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> {{user.username}}
  					</button>
					<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						<a class="dropdown-item" href="{% url 'accounts:profileView' %}">View Profile</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'accounts:logoutView' %}">Logout</a>
					</div>
				  </div>
			  </li>
				{% else %}
				<li class="nav-item dropdown">
					<div class="dropdown dropleft" style="margin-right:75px">
						<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item" href="{% url 'accounts:loginView' %}">View Profile</a>
							<a class="dropdown-item" href="#">Edit Profile</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'accounts:logoutView' %}">Login</a>
						</div>
					</div>
			  </li>
				{% endif %}
		      </li>
			</ul>
        </div>
    </nav>
	{% load static %}
	<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel" style="height: 300px;">
	  <ol class="carousel-indicators">
		<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
		<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
		<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	  </ol>
	  <div class="carousel-inner">
		<div class="carousel-item active" style="height: 300px;">
		  <img class="d-block w-100" src="{% static "Banners/Banner-1.PNG" %}" alt="Third slide">
			<div class="carousel-caption d-none d-md-block">
				<h5>Welcome to {{ tribe.tribeName }}!</h5>
				<p></p>
			</div>
		</div>
		<div class="carousel-item" style="height: 300px;">
		  <img class="d-block w-100" src="{% static "Banners/Banner-6.PNG" %}" alt="Third slide">
			<div class="carousel-caption d-none d-md-block">
				<h5>Post and Interact!</h5>
				<p></p>
			</div>
		</div>
		<div class="carousel-item" style="height: 300px;">
		  <img class="d-block w-100" src="{% static "Banners/Banner-5.PNG" %}" alt="Third slide">
			<div class="carousel-caption d-none d-md-block">
				<h5>Visit Tribe Houses!</h5>
				<p></p>
			</div>
		</div>
	  </div>
  	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
	</a>
  	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">

	<!-- Modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Message to tribe owner</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<form method="post">
                        {% csrf_token %}
                        {{ joinForm.message }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <input type="submit" value="Send"/>
                        </div>
                    </form>
                </div>
			</div>
		</div>
	</div>
	<div class="card">
		<div class="card-body">
			<h1 class="page-header" style="text-align:center; padding: 0.5em">{{ tribe.tribeName }} </h1>
			<hr>
			<h5><strong>About: </strong><p>{{ tribe.description }}</p></h5>
			<h5><strong>Tribe Owner: </strong>{{ tribe.tribeOwner }}</h5>
			<h5><strong>Tribe Members: </strong>
			{% for member in members %}
				{{ member.username }}
			{% endfor %}</h5>
		</div>
		<hr>

		<!-- Tribe Houses -->
		<div class="card-group" style="padding: 0.5em;">
		  <div class="card">
			<img class="card-img-top" src=".../100px180/" alt="Card image cap">
			<div class="card-body">
			  <h5 class="card-title">House of Swag</h5>
				{% if inTribe == True %}
			  <a class="btn btn-secondary" href="{% url 'tribes:tribeHousePage' tribe.tribeID %}" id="joinHouse1">Join House</a>
				{% endif %}
			</div>
		  </div>
		  <div class="card">
			<img class="card-img-top" src=".../100px180/" alt="Card image cap">
			<div class="card-body">
			  <h5 class="card-title">House of Tacos</h5>
			  {% if inTribe == True %}
			  <a class="btn btn-secondary" href="{% url 'tribes:tribeHousePage' tribe.tribeID %}" id="joinHouse2">Join House</a>
				{% endif %}
			</div>
		  </div>
		  <div class="card">
			<img class="card-img-top" src=".../100px180/" alt="Card image cap">
			<div class="card-body">
			  <h5 class="card-title">House of Wheeling</h5>
			  {% if inTribe == True %}
			  <a class="btn btn-secondary" href="{% url 'tribes:tribeHousePage' tribe.tribeID %}" id="joinHouse3">Join House</a>
				{% endif %}
			</div>
		  </div>
		<!-- End Tribe Houses -->
		</div>
	</div>
</div>
<!--Text-->
<div class="container" style="display: flex; flex: 1 1 100%;  flex-direction: row; flex-wrap: wrap;">

	<div class="card" style="flex:4 1 20%; text-align: left;overflow-y: scroll; height:50vh;">
		<div class="card-body">
			<h5 class="card-title">Upcoming Events</h5>

			<div class="card border-0 mb-4">
			  <a href="#"><img class="card-img-top" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img3.jpg" alt="wrappixel kit"></a>
			  <div class="date-pos bg-info-gradiant p-2 d-inline-block text-center rounded text-white position-absolute">Oct<span class="d-block">23</span></div>
			  <h5 class="font-weight-medium mt-3"><a href="#" class="text-decoration-none link">You should have eagle’s eye on new trends and techonogies</a></h5>
			  <p class="mt-3">Business Park, Opp. Corns Sam Restaurant, New Yoark, US</p>
			  <a href="#" class="text-decoration-none linking text-themecolor mt-2">Learn More</a>
			</div>
		</div>
	</div>

	<div class="card" style="flex:4 1 60%;overflow-y: scroll; height:60vh;">
            <div class="card-body">
                <h5 class="card-title" >Recent Posts in {{ tribe.tribeName }}
					{% if inTribe == True %}
					<a class="btn btn-secondary" data-toggle="modal" href="#tribePostModal" id="tribePost">Create Post</a>
					{% endif %}
				</h5>

				<!--Create Tribe Post Modal -->
				<div class="modal fade" id="tribePostModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLabel">Create New Post</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<form method="POST">
									{% csrf_token %}
									<label>Title</label>
									{{ createPostForm.title }}
									<label>Description</label>
									{{ createPostForm.description }}
									<label>Attach an image</label>
									{{ createPostForm.image }}
									<div class="modal-footer">
										<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
										<input type="submit" class="btn btn-secondary" value="Save Changes"/>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
				{% for p in posts %}
                <div class="card" style="margin-top:1%;">
                    <div class="card-header">
                        <div class="mr-2">
					{% load static %}

							<img class="rounded-circle" width="45" src="{% static "images/blankProfile.jpg" %}">
							<span style="margin-left: 5px;">{% for name in p.tribePosterID.all %}{{ name }}{% endfor %} of {% for name in p.postTribeID.all %}{{ name }}{% endfor %}</span>
                        </div>

						<h5 class="card-title" style="padding: 0.2em"> {{ p.title }} </h5>
						<div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i> {{ p.dateOfCreation }}</div>
						</div>
						<hr>

						<p class="card-text">
							{{ p.description }}
						</p>
						<div class="card-footer">
							<a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
							<a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
							<a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
						</div>
                </div>
				{% endfor %}
            </div>
        </div>
</div>
<!--Scripts go here-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script>
		$( "#editProfile" ).click(function() {
    		$('#exampleModal').modal('toggle');
		});
	</script>


</body>

</html>